# Generated by Django 3.1.7 on 2021-03-25 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='user.user'),
            preserve_default=False,
        ),
    ]
