# Generated by Django 3.1.7 on 2021-03-25 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_operation_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
    ]
